db:
  image: postgres:9.3
broker:
  image: rabbitmq
celery:
  build: .
  volumes:
    - .:/code
  links:
    - db
    - broker
  command: celery -A cardano worker -B -l debug
web:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - .:/app
  links:
    - db
  command:
    ./bin/run-dev.sh
